---
# Create  Server Profile Template for VCF Mgmt Hosts

- name: "Create IMM Server Profile Template for VCF Mgmt Hosts"
  vars:
    api_info: &api_info_org_moid
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info_org_moid
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ org_name }}'"
  register: intersight_org
  delegate_to: localhost
  tags: always
  run_once: true

# Collect information about various policies to be programmed into the Templates
- include_tasks: gather_policy_info.yml

# Create Server Profile Template for VCF Mgmt hosts using local boot
- include_tasks: create_server_profile_template.yml

# Create Server Profile Template for VCF Workload Daomin hosts using FC Boot from SAN
- include_tasks: create_fc_server_profile_template.yml