---
#
# Set NTP server
# Enable NTP Service
#
  - name: Configure ESXi NTP server
    vmware_host_ntp:
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      ntp_servers: '{{ item.ip_address }}'
    delegate_to: localhost
    with_list: "{{ ntp_servers }}"

  - name: Start ESXi ntpd for the hosts
    vmware_host_service_manager:
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: ntpd
      service_policy: on
    delegate_to: localhost
