---
# This file defines the Description for server profile template(s)
# These values typically do not need to changes but can be modified depending on customer requirements
# ---------------------------------------------------------------------------------------------------

description_of_SPT: "Server Profile Template for VCF Management Domain hosts"

description_of_fc_SPT: "Server Profile Template for VCF Workload Domain hosts"